FROM centos:7
RUN yum update -y

# Install OpenSSH server
RUN yum install -y openssh-server

# Install Ansible
RUN yum install -y epel-release && yum install -y git python-pip python-devel gcc libffi-devel openssl-devel
RUN pip install -U setuptools
RUN pip install 'ansible==1.9.6'

# Install Ansible inventory file
RUN mkdir /etc/ansible/ && echo -e "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
